### ISSUE TITLE
Take some rest between poll elements

### ISSUE THREAD

**Issue by nagyrobi** [safepay/sensor.fronius#23]
From time to time I get null values for various parameters. I suspect this must be because during each poll the inverter is stressed three times: inverter_data, powerflow_data and smartmeter_data are pulled immediately after each other, which may cause the small webserver embedded in the unit to lock up for a while.

![kép](https://user-images.githubusercontent.com/1550668/79471706-39ba7680-8003-11ea-9857-a7a34e6d4f57.png)
This is the graph of Fronius DC Current, for example. The gaps don't appear when using Home Assistant native fronius integration (which is disabled now).

I suggest to add a 5-second sleep between the consecutive data pulls somewhere around lines 107 and 115.

I'd do it but I've zero experience with proper python programming.

Using a Fronius Symo 3.7-3-M and a Smart Meter 63A.

**Comment by nilrog** [comment]
There is a problem in the code, that was amplified with a pull-request I made a few month ago that causes this, together with the fact that in some API endpoints the inverter returns 'null' as value when the inverter is not working.

I have made a correction for this in my fork, and asked a few to test it before I submit a pull-request for it. I have been running it for at least 2 weeks now and I do not see any '0' values for sensors where I previously did so.

If you want you can try my changes and see if these gaps goes away. Post back here and I can prepare a pull-request if it works for you too. My fork is up-to-date with this one so the only change is the one that should address this issue.
[https://github.com/nilrog/sensor.fronius](https://github.com/nilrog/sensor.fronius)

Just grab the sensor.py and replace the one you have and restart HA.

**Comment by nagyrobi** [comment]
OK, I just replaced my sensor.py with yours. I'll see how it behaves and post back.

**Comment by nagyrobi** [comment]
I think it's safe to prepare a pull-request because it works fine here.

**Comment by nilrog** [comment]
Ok, will do so this weekend. Thanks for the feedback :)
