### ISSUE TITLE
Adaptation to the new version oh home assistant

### ISSUE THREAD

**Issue by algernon2607** [safepay/sensor.fronius#40]
The new version of home assistant need modification of manifest.json . Without this modification , plugin will be disabled.
Can you help to repare this ??

**Comment by Martin-BW** [comment]
No 'version' key in the manifest file for custom integration 'fronius_inverter'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'fronius_inverter'

**Comment by algernon2607** [comment]
Thanks for the answer and the solution : i add version key : "version": "v0.9.3" in manifest.json and it works.
Congratulations

**Comment by colwilliamsnz** [comment]
Close. Resolved in later release.
