### ISSUE TITLE
Please add version key to the manifest file. Else, as of june 2021 the component will not load anymore

### ISSUE THREAD

**Issue by Horsi70** [safepay/sensor.fronius#46]
Hello,
Please add the version key to the manifest file, cause as of homeassistant version 2021.6 (June 2021), the version key is required to load a component. I have seen you have responded to another request that in v0.9.3 the version has been added. I have installed v0.9.3 but I still get the following message.

Thanks a lot in advance
Regards

Logger: homeassistant.loader
Source: loader.py:786
First occurred: 12:07:22 (1 occurrences)
Last logged: 12:07:22

No 'version' key in the manifest file for custom integration 'fronius_inverter'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'fronius_inverter'

**Comment by der-optimist** [comment]
Hello, 
I vote for that, too... please update the manifest file in this repo.
In the meantime, @Horsi70 you can add the version key manually to the file as it is decribed in the other issue report.
On your local HA system, go to custom_components folder and add this line to the already existing keys in manifest.json:
"version": "v0.9.3",
This works for me, but of course a "clean" solution would be better.
Thanks for your work, @safepay

**Comment by Horsi70** [comment]
Hello,
adding the file myself to the manifest file would be one of the options.
I added the repository from cathelest and installed his version. It already contains the version in the manifest.
But as said, a "clean" solution would be better. 
Thanks

**Comment by colwilliamsnz** [comment]
Close. Resolved in later release.
