### ISSUE TITLE
Added pause of polling from sunset to sunrise

### ISSUE THREAD

**Issue by cathelest** [safepay/sensor.fronius#5]
Hello Safepay, Thanks again for working on this,

As per your comments, my powerflow seems to stop working during sundown, 

Im sure making the times as you have it the "default" is probably best for most users which only have the inverter and not the smart meter,

But,  I have the smart meter, and would love to see stats during the night please,

Can you add an option to disable the timer,

On a side note, the configurator checker kept throwing errors anytime i tried to use the end_time config line,

**Invalid config for [sensor.fronius_inverter]: [end_time] is an invalid option for [sensor.fronius_inverter]. Check: sensor.fronius_inverter->end_time. (See ?, line ?). Please check the docs at https://home-assistant.io/components/sensor.fronius_inverter/**

**Comment by safepay** [comment]
Thanks for the feedback.

I have made a small adjustment to ignore the pause if the sensor is from the Powerflow device.

The issue for the bug in times will just be config.

Make sure you have quotes around the times. E.g.
```yaml
    stop_time: '12:31'
```
