### ISSUE TITLE
version field not updated in the manifest.json file

### ISSUE THREAD

**Issue by lrybak** [safepay/sensor.fronius#51]
manifest.json file is not updated to the newest version (0.9.5) accordingly

`{
  "domain": "fronius_inverter",
  "name": "Fronius",
  "documentation": "https://github.com/safepay/sensor.fronius/blob/master/README.md",
  "dependencies": [],
  "codeowners": ["@safepay"],
  "requirements": [],
  "version": "v0.9.3"
}`

**Comment by colwilliamsnz** [comment]
Closing. Fixed in later release.
