### ISSUE TITLE
Failed to update: connection error

### ISSUE THREAD

**Issue by Yagu-znal** [safepay/sensor.fronius#53]
Thank you for this integration and your work! Great stuff!

In my log I get this error:
`Failed to update: connection error`
and the relevant sensors stay unknown

Fronius firmware:
```
Datalogger ID: 240.1147052
Software version: 3.16.7-1
Search for Firmware Update
Fronius Solar Net connection: Connected
Solar.web connection: Connected
```

Fronius integration v0.9.5
HA Config:
```
  - platform: fronius_inverter
    ip_address: http://192.168.1.25
```

When I go to the address mentioned in your readme I get a 404 error but both urls mentioned below it do work. 
http://<froniusip>/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=CommonInverterData
`404 Not Found`

I really need the array voltage and amperage so I do hope to get this working again.

**Comment by HomeAsst** [comment]
hi, 
I just installed this awesome integration but I have the same issue.

I installed it using HACS and the log says:
2021-07-16 15:05:51 ERROR (MainThread) [custom_components.fronius_inverter.sensor] Failed to update: connection error
2021-07-16 15:05:56 ERROR (MainThread) [custom_components.fronius_inverter.sensor] Failed to update: connection error

@Yagu-znal, the link in the gitHun page is not correct but it is correct in the sensor.py

just try: http://{YOUR_IP_ADDRESS}/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=0&DataCollection=CommonInverterData.

@safepay - Riccardo please can you help us out here. Grazie mille

Matt

**Comment by HomeAsst** [comment]
Hi, 
I found the solution. in the config.yaml file you need to specify the ip address without http://
that was my mistake as well

- platform: fronius_inverter
    ip_address: 192.168.1.25

and you should be good to go

**Comment by speedracer1190** [comment]
Thanks for this!   this was also my issue as well,  I assume the http:// parameter was added to the code since a lot of youtube walk throughs.

**Comment by Yagu-znal** [comment]
I edited line 23 in /config/custom_components/fronius_inverter/sensor.py to 
`_INVERTERRT = 'http://<realfroniusip>/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=CommonInverterData'`
I 'hardcoded' the fronius ip in the script itself. It works now.
