### ISSUE TITLE
device_state_attributes

### ISSUE THREAD

**Issue by Bascht74** [safepay/sensor.fronius#82]
I get the following log in HA:

`2022-01-07 11:21:20 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.fronius_west_ig_tl_3_6_ac_power (<class 'custom_components.fronius_inverter.sensor.FroniusSensor'>) implements device_state_attributes. Please report it to the custom component author.
`

See: 
http://dev-docs.home-assistant.io/en/master/api/helpers.html

> property device_state_attributes
> Return entity specific state attributes.
> 
> This method is deprecated, platform classes should implement extra_state_attributes instead.

Could you change your integration to the new method?

**Comment by djsheetu** [comment]
I am having the same issue for a couple of days as well. Please see if you can update the integration.
Thanks.

**Comment by Bascht74** [comment]
no reaction
